name: book_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: 
  shared_preferences: ^0.5.4+5
  page_transition: ^1.1.5
  flutter_icons: ^1.0.0+1
  cached_network_image: ^2.0.0
  path_provider: ^1.4.0
  objectdb: ^1.0.7+1
  epub_kitty: ^0.1.6
  uuid: ^2.0.4
  permission_handler: ^4.2.0+hotfix.1
  dio: ^3.0.8
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - res/images/splash/splash0.jpg
   - res/images/splash/splash1.jpg
   - res/images/splash/splash2.jpg
   - res/images/splash/splash3.jpg
   - res/images/other/place.png
   - res/images/other/empty.png
   - res/images/other/icon_logo.png
   - res/images/shelf/coupe.jpg
   - res/images/shelf/douban.jpg
   - res/images/shelf/essay.jpg
   - res/images/shelf/fiction.jpg
   - res/images/shelf/history.jpg
   - res/images/shelf/inference.jpg
   - res/images/shelf/life.png
   - res/images/shelf/mental.jpg
   - res/images/shelf/novel.jpg
   - res/images/shelf/skill.jpg
   - res/images/shelf/wall.png


